name: release
on:
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  release:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: 1.19
      - run: make test
      - run: make login
      - run: make build
      - run: make push
